<?php
// =========================================================
// Shopify SEO — service page
// =========================================================
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../includes/functions.php';

$service = [
    'slug'        => 'shopify-seo',
    'title'       => 'Shopify SEO',
    'pill'        => 'Platform &amp; Ecommerce',
    'metaTitle'   => 'Shopify SEO Services | Weblo',
    'metaDesc'    => 'Fix app bloat, duplicate collection pages, and Shopify\'s built-in SEO limits. Practical audits built for how Shopify stores actually work.',
    'h1'          => 'Work Within Shopify&rsquo;s Limits, Not Against Them',
    'lead'        => 'Shopify makes it easy to launch a store and hard to control some of the things SEO depends on. We manage the fixable gaps &mdash; and tell you plainly which things are just how the platform works.',
    'image'       => 'assets/img/blog/popular1.jpg',
    'imageAlt'    => 'Shopify SEO - app performance and duplicate collection page audit',
    'related'     => ['wordpress-seo', 'technical-seo-audits', 'aeo-geo'],

    'intro' => [
        'Shopify makes it easy to launch a store and hard to control some of the things SEO depends on. You can&rsquo;t remove /products/ or /collections/ from your URL structure. You can&rsquo;t touch the checkout page. Every app you install drops its own script into the theme, whether you need it running on every page or not.',
        'None of this is a flaw in Shopify. It&rsquo;s the tradeoff of a hosted platform. <strong>Shopify SEO work</strong> is about the fixes that are possible within those constraints &mdash; and knowing which problems are actually worth solving versus which are just how the platform works.',
    ],

    'split' => [
        'kicker'    => 'Apps &bull; Duplicates &bull; Liquid',
        'lead'      => 'We audit what&rsquo;s installed and what it&rsquo;s doing to page weight and rendering, then fix the collection and product structure issues the platform creates by design.',
        'image'     => 'assets/img/blog/popular1.jpg',
        'imageAlt'  => 'Shopify SEO - app audit and duplicate content review',
        'points'    => [
            ['icon' => 'ri-puzzle-2-line', 'title' => 'App &amp; script audit', 'text' => 'Which installed apps are adding load time &mdash; and where that load time actually matters versus where it doesn&rsquo;t.'],
            ['icon' => 'ri-file-copy-line', 'title' => 'Duplicate content review', 'text' => 'A single product accessible through multiple collection URLs, plus faceted navigation generating thousands of near-duplicate indexable URLs.'],
            ['icon' => 'ri-code-s-slash-line', 'title' => 'Liquid template review', 'text' => 'How metadata, headings, and internal links are generated by the theme by default &mdash; a lot of Shopify SEO issues come from theme defaults.'],
            ['icon' => 'ri-arrow-right-left-line', 'title' => 'Redirect coverage', 'text' => 'For migrated stores or restructured collections, closing the gaps in Shopify&rsquo;s built-in redirect handling.'],
        ],
        'matters'   => [
            ['icon' => 'ri-scales-3-line', 'title' => 'Not every duplicate is urgent', 'text' => 'Shopify creates some duplication by design. We find which instances actually hurt visibility and which are just how collections work.'],
            ['icon' => 'ri-rocket-line', 'title' => 'Speed tested where it matters', 'text' => 'A fast homepage doesn&rsquo;t mean product pages are fast. We check the templates that carry the traffic.'],
            ['icon' => 'ri-shopping-bag-3-line', 'title' => 'Product pages feed AI shopping', 'text' => 'Product content is the type most likely to get pulled into AI shopping assistants, which is covered on our <a href="' . site_url('aeo-geo') . '">AEO &amp; GEO</a> page.'],
        ],
    ],

    'sections' => [
        [
            'heading' => 'Where Shopify stores usually lose visibility',
            'paras'   => [
                'The most common issue is duplicate content that comes from the platform&rsquo;s own structure. Shopify&rsquo;s default canonical handling covers a lot of it, but it&rsquo;s easy for a theme customization to break that without anyone noticing &mdash; which is why checking rather than assuming matters.',
                'App bloat is the other recurring problem. A store running five or six apps for reviews, currency conversion, upsells, and live chat is often carrying render-blocking scripts on every page load, even on pages where that functionality doesn&rsquo;t matter. This shows up directly in Core Web Vitals, and it&rsquo;s rarely obvious from looking at the store itself.',
                'Then there&rsquo;s pagination and filtering. On a store with a few hundred products, unmanaged faceted navigation can multiply into thousands of near-duplicate URLs competing with each other for the same search terms.',
            ],
        ],
        [
            'heading' => 'What&rsquo;s included',
            'points'  => [
                ['icon' => 'ri-puzzle-2-line', 'title' => 'App performance audit', 'text' => 'Identifying which apps justify their weight and which can be replaced with a lighter setup or removed entirely.'],
                ['icon' => 'ri-file-copy-line', 'title' => 'Duplicate &amp; indexation fixes', 'text' => 'Canonical and indexation recommendations across products, collections, and filtered navigation.'],
                ['icon' => 'ri-code-s-slash-line', 'title' => 'Theme &amp; redirect review', 'text' => 'How metadata and headings are generated, plus redirect coverage for migrated or restructured stores.'],
                ['icon' => 'ri-shopping-bag-3-line', 'title' => 'Product page structure', 'text' => 'Reducing thin or duplicate category content and checking product schema accuracy.'],
            ],
        ],
        [
            'heading' => 'Who this is for',
            'points'  => [
                ['icon' => 'ri-rocket-line', 'title' => 'Slow stores', 'text' => 'Page speed dragging from app accumulation, or a visible slowdown after a theme change or app install.'],
                ['icon' => 'ri-file-copy-line', 'title' => 'Duplicate content', 'text' => 'Duplicate content across products and collections, or a catalog that outgrew its structure.'],
                ['icon' => 'ri-refresh-line', 'title' => 'Post-migration drops', 'text' => 'A drop in visibility after a theme change, app install, or platform migration.'],
            ],
        ],
    ],

    'faqs' => [
        ['q' => 'Can you actually fix Shopify\'s URL structure?', 'a' => 'No, and we won\'t pretend otherwise. The /products/ and /collections/ structure is fixed at the platform level. What we can do is manage the duplicate content and indexation issues that structure creates, mainly through canonical tags and controlled indexing rather than structural changes.'],
        ['q' => 'Will this slow down our store while you work on it?', 'a' => 'No. Most of the audit work happens without touching the live theme. Implementation changes are staged and tested before going live, particularly anything involving app removal or theme edits.'],
        ['q' => 'Do you work with Shopify Plus or headless setups?', 'a' => 'For heavily customized or headless builds, the work looks closer to our Enterprise SEO service, since the technical constraints are different from a standard Shopify theme.'],
        ['q' => 'How is this different from your Technical SEO service?', 'a' => 'Technical SEO covers crawlability and indexation on any platform. This page focuses on what\'s specific to Shopify: app-driven performance issues, collection and product duplication, and theme-level defaults that are unique to how Shopify stores are built.'],
        ['q' => 'Do you help with product page copy too?', 'a' => 'Yes, where it\'s part of the engagement. Product and category content work is covered under our On-Page SEO service and often gets bundled in when thin content is part of what\'s limiting visibility.'],
    ],

    'ctaTitle' => 'Start with a working conversation',
    'ctaLead'  => 'If your Shopify store is dealing with slow page speed, duplicate collection pages, or a visibility drop after a theme or app change, request a free SEO analysis and we&rsquo;ll walk through what&rsquo;s actually going on.',
];

// ---------------------------------------------------------
// Unique store-triage layout for this service (no shared layout).
// ---------------------------------------------------------
require __DIR__ . '/_page-head.php';
?>
<!-- ========== PAGE HERO ========== -->
<section class="page-hero section">
	<div class="container">
		<nav class="hs-breadcrumb fadeInUp" data-delay="0.05" aria-label="Breadcrumb">
			<a href="<?= site_url('') ?>">Home</a><i class="ri-arrow-right-s-line"></i>
			<a href="<?= site_url('') ?>#services">Services</a><i class="ri-arrow-right-s-line"></i>
			<span><?= e($service['title']) ?></span>
		</nav>
		<div class="col-lg-9 col-xs-12 mx-auto text-center fadeInUp" data-delay="0.1">
			<h3 class="pill"><i class="<?= e($SERVICES[$service['slug']]['icon']) ?>"></i><?= e($service['pill']) ?></h3>
			<h1><?= e($service['h1']) ?></h1>
			<p class="sec-lead mx-auto" style="max-width:780px;"><?= $service['lead'] ?></p>
			<div class="svc-kicker-row">
				<span class="svc-kicker"><i class="ri-puzzle-2-line"></i>App &amp; script audit</span>
				<span class="svc-kicker"><i class="ri-file-copy-line"></i>Duplicate review</span>
				<span class="svc-kicker"><i class="ri-code-s-slash-line"></i>Liquid templates</span>
				<span class="svc-kicker"><i class="ri-arrow-right-left-line"></i>Redirect coverage</span>
			</div>
		</div>
	</div>
</section>

<!-- ========== SIGNATURE QUOTE ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="svc-quote fadeInUp" data-delay="0.1">
			<i class="ri-double-quotes-l"></i>
			<p>Shopify makes it easy to launch a store &mdash; and hard to control some of the things SEO depends on.</p>
			<span>We manage the fixable gaps, and tell you plainly which things are just how the platform works.</span>
		</div>
	</div>
</section>

<!-- ========== INTRO ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="svc-intro fadeInUp" data-delay="0.1">
			<?php foreach ($service['intro'] as $p): ?>
				<p><?= $p ?></p>
			<?php endforeach; ?>
		</div>
	</div>
</section>

<!-- ========== APP TRIAGE TABLE ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="svc-section fadeInUp" data-delay="0.1">
			<h2 class="svc-section-title">Triage an <span style="color:var(--primary-color);">app stack</span></h2>
			<p class="svc-section-lead">This is how we think about every script a store is carrying &mdash; not &ldquo;apps are bad,&rdquo; just: what is this costing every page load?</p>
			<div class="svc-table-wrap">
				<table class="svc-table">
					<tr><th>App type</th><th>Where it loads</th><th>Cost to the store</th><th>Verdict</th></tr>
					<tr><td>Reviews &amp; ratings</td><td>Product pages</td><td>Third-party script on every product load</td><td><span class="tag med">Audit</span></td></tr>
					<tr><td>Currency converter</td><td>All pages</td><td>Regional need, but it ships an extra script site-wide</td><td><span class="tag bad">Trim</span></td></tr>
					<tr><td>Upsells &amp; cross-sells</td><td>Cart / product</td><td>Only matters at purchase; still renders everywhere</td><td><span class="tag med">Audit</span></td></tr>
					<tr><td>Live chat</td><td>All pages</td><td>Render-blocking script across the whole store</td><td><span class="tag bad">Trim</span></td></tr>
					<tr><td>Core platform apps</td><td>Theme-level</td><td>Needed, but configuration can be trimmed</td><td><span class="tag good">Keep</span></td></tr>
				</table>
			</div>
			<p>Stores running several of these are often paying a Core Web Vitals tax on every page &mdash; the kind of slowdown that shows up on product pages, not the homepage. Fixes here also matter for how product content gets pulled into AI shopping answers, covered on <a href="<?= site_url('aeo-geo') ?>">AEO &amp; GEO</a>.</p>
		</div>
	</div>
</section>

<?php $s = $service['split']; ?>
<!-- ========== STORE HEALTH (dark split) ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="seo-content-wrap fadeInUp" data-delay="0.1">
			<div class="row no-gutters">
				<div class="col-lg-7">
					<div class="seo-content-left">
						<h3 class="pill" style="color:#fff;border-color:rgba(255,255,255,.25);"><i class="<?= e($SERVICES[$service['slug']]['icon']) ?>"></i><?= e($s['kicker']) ?></h3>
						<h2>Inside the <span style="color:var(--primary-color);">Store Health Check</span></h2>
						<?php if (!empty($s['lead'])): ?><p class="seo-lead"><?= $s['lead'] ?></p><?php endif; ?>
						<?php foreach ($s['points'] as $pt): ?>
						<div class="seo-feature-item">
							<div class="seo-icon"><i class="<?= e($pt['icon']) ?>"></i></div>
							<div>
								<h3><?= $pt['title'] ?></h3>
								<p><?= $pt['text'] ?></p>
							</div>
						</div>
						<?php endforeach; ?>
					</div>
				</div>
				<div class="col-lg-5">
					<div class="seo-content-right">
						<h3>What we&rsquo;re honest about</h3>
						<?php foreach ($s['matters'] as $m): ?>
						<div class="seo-point">
							<i class="<?= e($m['icon']) ?>"></i>
							<div>
								<strong><?= $m['title'] ?></strong>
								<span><?= $m['text'] ?></span>
							</div>
						</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- ========== WHAT'S INCLUDED ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="svc-section fadeInUp" data-delay="0.1">
			<h2 class="svc-section-title"><?= e($service['sections'][1]['heading']) ?></h2>
			<div class="row">
				<?php foreach ($service['sections'][1]['points'] as $pt): ?>
				<div class="col-lg-4 col-md-6 col-sm-12 px-lg-3 mb-4">
					<div class="feature-card h-100">
						<i class="<?= e($pt['icon']) ?>"></i>
						<h4><?= $pt['title'] ?></h4>
						<p><?= $pt['text'] ?></p>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</section>

<!-- ========== FIX ORDER STEPS ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="sec-header center fadeInUp" data-delay="0.1">
			<h3 class="pill"><i class="ri-list-check-2"></i>Rollout</h3>
			<h2 class="sec-title">The Fix <span>Order</span></h2>
			<p class="sec-lead">Staged and tested before anything touches the live theme &mdash; most audit work runs without slowing the store.</p>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-12 mb-5">
				<div class="step-card fadeInUp" data-delay="0.1">
					<div class="step-circle"><i class="ri-puzzle-2-line"></i><span class="step-num">1</span></div>
					<h4>Triage apps</h4>
					<p>Identify which apps justify their weight and which can be replaced with a lighter setup.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-12 mb-5">
				<div class="step-card fadeInUp" data-delay="0.2">
					<div class="step-circle"><i class="ri-file-copy-line"></i><span class="step-num">2</span></div>
					<h4>Fix duplicates</h4>
					<p>Canonical and indexation work across products, collections, and faceted navigation.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-12 mb-5">
				<div class="step-card fadeInUp" data-delay="0.3">
					<div class="step-circle"><i class="ri-code-s-slash-line"></i><span class="step-num">3</span></div>
					<h4>Verify templates</h4>
					<p>Check that metadata, headings, and internal links are generated the way they should be.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-12 mb-5">
				<div class="step-card fadeInUp" data-delay="0.4">
					<div class="step-circle"><i class="ri-arrow-right-left-line"></i><span class="step-num">4</span></div>
					<h4>Cover migrations</h4>
					<p>Close the gaps in redirect handling for migrated stores and restructured collections.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- ========== WHO THIS IS FOR ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="svc-section fadeInUp" data-delay="0.1">
			<h2 class="svc-section-title"><?= e($service['sections'][2]['heading']) ?></h2>
			<div class="row">
				<?php foreach ($service['sections'][2]['points'] as $pt): ?>
				<div class="col-lg-4 col-md-6 col-sm-12 px-lg-3 mb-4">
					<div class="feature-card h-100">
						<i class="<?= e($pt['icon']) ?>"></i>
						<h4><?= $pt['title'] ?></h4>
						<p><?= $pt['text'] ?></p>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
			<p class="text-center mt-2">On WordPress rather than Shopify? The <a href="<?= site_url('wordpress-seo') ?>">WordPress SEO</a> page covers the equivalent platform-specific causes there.</p>
		</div>
	</div>
</section>

<!-- ========== FAQ ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="sec-header center fadeInUp" data-delay="0.1">
			<h3 class="pill"><i class="ri-question-answer-line"></i>FAQ</h3>
			<h2 class="sec-title">Frequently Asked <span>Questions</span></h2>
		</div>
		<div class="row">
			<div class="col-lg-8 col-md-12 mb-4 order-lg-2">
				<div class="accordion-holder fadeInUp" data-delay="0.3">
					<?php foreach ($service['faqs'] as $i => $faq) { $open = $i === 0 ? 'true' : 'false'; ?>
						<div class="accordion-item" data-open="<?= $open ?>">
							<h3 class="accordion-header"><?= $faq['q'] ?><span></span></h3>
							<div class="accordion-body"><p><?= $faq['a'] ?></p></div>
						</div>
					<?php } ?>
				</div>
			</div>
			<div class="col-lg-4 col-md-12 mb-4 order-lg-1">
				<div class="faq-wrap fadeInUp" data-delay="0.2">
					<i class="ri-question-answer-line"></i>
					<h2>Have a different question?</h2>
					<a href="<?= site_url('contact') ?>" class="btn btn-primary mb-2">Get a free assessment</a>
					<p>Prefer to email? <a href="mailto:<?= e(CONTACT_EMAIL) ?>"><?= e(CONTACT_EMAIL) ?></a></p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- ========== RELATED (internal links into other services) ========== -->
<?php if (!empty($related)): ?>
<section class="section pt-0">
	<div class="container">
		<div class="sec-header center fadeInUp" data-delay="0.1">
			<h3 class="pill"><i class="ri-arrow-right-up-line"></i>Related Services</h3>
			<h2 class="sec-title">Explore More <span>Ways We Help</span></h2>
			<p class="sec-lead">This service rarely works alone. These are the areas it connects with most.</p>
		</div>
		<div class="row">
			<?php foreach ($related as $i => $r): ?>
			<div class="col-lg-4 col-md-4 col-sm-12 mb-4">
				<a class="industry-card fadeInUp" href="<?= site_url($r['slug']) ?>" data-delay="<?= min(0.1 + $i * 0.12, 0.4) ?>">
					<div class="industry-icon"><i class="<?= e($r['icon']) ?>"></i></div>
					<h4><?= e($r['name']) ?></h4>
					<p><?= e($r['tagline']) ?></p>
					<span class="industry-link">Explore service <i class="ri-arrow-right-s-line"></i></span>
				</a>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
</section>
<?php endif; ?>

<!-- ========== CTA ========== -->
<section class="section pt-0">
	<div class="container">
		<div class="cta-band fadeInUp" data-delay="0.1">
			<div class="row align-items-center">
				<div class="col-lg-7 col-md-12 mb-4 mb-lg-0">
					<h2><?= e($service['ctaTitle']) ?></h2>
					<p><?= $service['ctaLead'] ?></p>
				</div>
				<div class="col-lg-5 col-md-12 text-lg-right">
					<a href="<?= site_url('audit') ?>" class="btn btn-white mb-2">Free Automated Audit</a>
				</div>
			</div>
		</div>
	</div>
</section>
<?php require __DIR__ . '/../includes/footer.php';